(ql:quickload :dbi)
(ql:quickload :clack)
(ql:quickload :lack)
(ql:quickload :lack-request)
(ql:quickload :lack-middleware-session)
(ql:quickload :lack-middleware-accesslog)
(ql:quickload :hunchentoot)
(ql:quickload :ironclad)
(ql:quickload :jonathan)
(ql:quickload :cl-json)
(ql:quickload :uuid)


(defmacro load-file (file-path)
  `(load (merge-pathnames (make-pathname :directory '(:relative ,file-path)))))


(load-file "./utils/string-util.lisp")
(load-file "./utils/response-util.lisp")
(load-file "./utils/datetime.lisp")
(load-file "./utils/file-util.lisp")
(load-file "./models/location.lisp")
(load-file "./models/user.lisp")
(load-file "./models/access-token.lisp")
(load-file "./database/connection.lisp")
(load-file "./repositories/user-repository.lisp")
(load-file "./repositories/location-repository.lisp")
(load-file "./repositories/access-token-repository.lisp")
(load-file "./utils/environment-util.lisp")
(load-file "./controllers/user-controller.lisp")
(load-file "./controllers/location-controller.lisp")
(load-file "./controllers/access-token-controller.lisp")
(load-file "./middlewares/access-token-handler-middleware.lisp")
(load-file "./app.lisp")
